// News Headline Action Types
export const SET_NEWS_API_HEADLINE = "SET_NEWS_API_HEADLINE"
export const SET_NEWS_API_HEADLINE_SUCCESS = 'SET_NEWS_API_HEADLINE_SUCCESS';
export const SET_NEWS_API_HEADLINE_FAILURE = 'SET_NEWS_API_HEADLINE_FAILURE';

// News Categories Setter
export const SET_NEWS_CATEGORIES_HEADLINE = "SET_NEWS_CATEGORIES_HEADLINE"

// News Filtered Action Types
export const SET_FILTERED_NEWS_API = "SET_FILTERED_NEWS_API"
export const UNMOUNT_FILTERED_NEWS_API = "UNMOUNT_FILTERED_NEWS_API"