// News Headline Action Types
export const SET_NEWS_API_HEADLINE = "SET_NEWS_API_HEADLINE"
export const SET_NEWS_API_HEADLINE_SUCCESS = 'SET_NEWS_API_HEADLINE_SUCCESS';
export const SET_NEWS_API_HEADLINE_FAILURE = 'SET_NEWS_API_HEADLINE_FAILURE';