// News Headline Action Types
export const SET_NEWS_HEADLINE = "SET_NEWS_HEADLINE"
export const SET_NEWS_HEADLINE_SUCCESS = 'SET_NEWS_HEADLINE_SUCCESS';
export const SET_NEWS_HEADLINE_FAILURE = 'SET_NEWS_HEADLINE_FAILURE';

// News Categories Setter
export const SET_NEWS_CATEGORIES_HEADLINE = "SET_NEWS_CATEGORIES_HEADLINE"

// News Filtered Action Types
export const SET_FILTERED_NEWS = "SET_FILTERED_NEWS"
export const SET_FILTERED_NEWS_SUCCESS = 'SET_FILTERED_NEWS_SUCCESS';
export const SET_FILTERED_NEWS_FAILURE = 'SET_FILTERED_NEWS_FAILURE';
export const UNMOUNT_FILTERED_NEWS = "UNMOUNT_FILTERED_NEWS"